### ISSUE TITLE
Q-draggable table with columns that have colspan

### ISSUE THREAD

**Issue by tomi2605** [bd2051/q-draggable-table#2]
How can I make this draggable table work with columns that have colspan?
I have tried, but it doesn't allow dragging when there are columns with colspan

**Comment by bd2051** [comment]
After checking, I did not find confirmation of the problem. The library works with the table-colspan property. See for yourself here 
https://codesandbox.io/p/devbox/agitated-bogdan-tngniw?file=%2Fsrc%2Fpages%2FVirtualScroll.vue . Page virtual-scroll, third table. Perhaps you need to make sure that your onDrop callback is correct. If the problem persists, describe the problem in more detail and send your code

**Comment by bd2051** [comment]
Please note that the library itself does not move columns. It provides column indexes for moving. The final redrawing is carried out due to the reactivity of vue

**Comment by tomi2605** [comment]
i can drag the column, but after release or drop in new area the column not move in drop area.
i not see any error message in console.
this my sample code

<q-table class="my-sticky-header-table" style="height: 100%" :table-header-class="tableColor"
  table-class="bg-white text-black" :rows="listTask" :columns="columns" row-key="urut" :key="tableKey"
  v-model:pagination="pagination" :loading="loading" :filter="pagination.filter"
  :rows-per-page-options="[]" :expanded="expanded" :hide-pagination="true" @request="onRequest"
  virtual-scroll virtual-scroll-sticky-size-start="1" binary-state-sort separator="cell"  v-draggable-table="{
    onDrop: onDropColSpan,
    options: {
      fixFirstColumn: true,
    },
  }">

**Comment by tomi2605** [comment]
Sorry, I just found the issue. After updating Quasar to version 2.16, all drag functions work normally.
Thank you!
